name: Continuous Integration

on: 
  pull_request:
    branches:
      [ develop ]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run install, build and test
        uses: |
          npm install
          npm run build
          npm run test